### ISSUE TITLE
Project Contribution by Hikmah

### ISSUE THREAD

**Issue by Muhammadzubair26** [zuri-training/Team_87_zuri_fetch_metadata#27]
Hi Hikmah, you were assigned the following tasks: Working on the empathy map, feature set, Hi-fi designs, and prototyping. Please outline how you went about your assignment, the issues you faced and how you went about resolving them

**Comment by Hi-show** [comment]
Hi Muhammad, my work starts here:

              Tasks With Team Members
1.  User Research: where I didn't work too much on it because I wasn't assigned the task, all I did was assisted in drafting Research Questions when it was urgently needed, I drafted this research question based on the metadata Idea and the problem statement perceived and the research question is based on questioning ourselves on how we designers can better solve our Users problems on metadata by creating good features, good User interface and to have a seamless experience.

2.  Empathy Map: After getting our research results all together from the interview, I and my team members empathized with our ideal users by knowing what they said, what they think, what they did and how they felt. So this helped us understand their pains and frustrations that made us carry out our User persona.

3.  User Persona: the User persona showed us who our ideal users really are, and assist us in identifying them, their interests, pains and frustrations and it gives us a sense of direction of how to tackle their problems. 

4.  Brainstorming and Prioritization Matrix: This was also done by I and my team members, where we all brainstormed on how to really solve our User's problem and came up with different ideas and features (good and bad).
    Then we made a prioritizization Matrix and sorted out the ideas and features according to their priorities and which ones are most important to our Users and be done first. That was where we came up with the features to be used for our website.

Below is the Figjam file I and my team worked on:
https://www.figma.com/file/7e3uc3O4z5Na53W3ypLTT6

                  The Tasks I did Myself 
1.  User flow: I personally, did this user flow myself, then my team members checked for review. Most of the way I designed the flow was accepted by them all.
     This user flow I did, gave us a sense of direction of how to design our website and arrange the pages for easy use and easy journey of the website by the users.

Below shows the link where I designed the User flow :  https://www.figma.com/file/7e3uc3O4z5Na53W3ypLTT6

2.  Extract Metadata Page: The extract metadata page was designed by me (Desktop screen, Tablet screen and Mobile screen) both Lo Fi and Hi Fi

3. Prototype: I did the prototype for all the screens (Desktop screens, Tablet screens and Mobile screens) from start to finish. Below are the links of prototype I did for the three screens

Desktop screens:

https://www.figma.com/proto/CkM3iUeJbQPQpanFVs85xx/Team-87-Fetch-Metadata?page-id=54%3A393&node-id=1564%3A17019&viewport=474%2C-1385%2C0.03&scaling=scale-down&starting-point-node-id=1564%3A17019&show-proto-sidebar=1

Tablet screens: 

https://www.figma.com/proto/CkM3iUeJbQPQpanFVs85xx/Team-87-Fetch-Metadata?page-id=54%3A393&node-id=1573%3A99296&viewport=474%2C-1385%2C0.03&scaling=scale-down&starting-point-node-id=1573%3A99296&show-proto-sidebar=1

Mobile screens:

https://www.figma.com/proto/CkM3iUeJbQPQpanFVs85xx/Team-87-Fetch-Metadata?page-id=54%3A393&node-id=1567%3A21743&viewport=474%2C-1385%2C0.03&scaling=scale-down&starting-point-node-id=1567%3A21743&show-proto-sidebar=1
